In [1]:
import numpy as np

In [2]:
array=np.zeros(10)
print("10 nuley:")
print(array)

10 nuley:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
array=np.ones(10)
print("10 edinic")
print(array)

10 edinic
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
array=np.ones(10)*5
print("10 pyaterok:")
print(array)

10 pyaterok:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
array=np.arange(10,51)
print("ot 10 do 50:")
print(array)

ot 10 do 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
array=np.arange(10,51,2)
print("ot 10 do 50:")
print(array)

ot 10 do 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [8]:
matric =  np.arange(0, 9).reshape(3,3)
print(matric)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
matric = np.eye(3)
print(matric)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
rand=np.random.random(1)[0]
print("ot 0 do 1")
print(rand)

ot 0 do 1
0.5100493277444974


In [22]:
rand = np.random.normal(0,1,15)
print("15 random numbers:")
print(rand)

15 random numbers:
[ 1.1884904   1.82021697  0.19670193 -0.01570956  0.87045645  2.03421857
  0.05167491 -0.55246126  1.44347351 -0.20675176  0.44288914 -1.11965281
 -0.50049069  0.50621496 -0.60975767]


In [25]:
matric =  np.arange(0, 1).reshape(10,10)
print(matric)

ValueError: ignored